services:
    monitix:
        container_name: monitix
        environment:
            - USERNAME=admin
            - PASSWORD=admin
            - EMAIL=admin@admin.de
            - DEBUG=True
            - APP_URL=http://127.0.0.1:6753
            - TIMEZONE=Europe/Berlin
        ports:
            - "6753:6753"
        build:
            dockerfile: docker/Dockerfile
            context: ../../
        volumes:
            - ./data:/app/data
        depends_on:
            - agent

    agent:
        container_name: monitix_agent
        build:
            dockerfile: agent/Dockerfile
            context: ../../
        environment:
            - HOST_PROC=/host/proc
            - HOST_SYS=/host/sys
            - AUTH_KEY=vbuipiubtwuivbriuevrbuigb4iu
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8084:8080
        privileged: true
