# Generated by Django 5.2.2 on 2025-06-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.PositiveIntegerField(default=4589)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('ssh_key', models.TextField(blank=True, null=True)),
                ('auth_type', models.CharField(choices=[('password', 'Password'), ('key', 'SSH Key')], default='password', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
