# Generated by Django 5.2.2 on 2025-06-12 20:22

import django.core.validators
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[A-Fa-f0-9]{6}')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='server',
            name='password',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.PositiveIntegerField(default=4589, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='ssh_key',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='servers', to='ServerManager.tag'),
        ),
    ]
