# Generated by Django 5.2.2 on 2025-06-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManager', '0002_tag_alter_server_password_alter_server_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_ping',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ping_successful',
            field=models.BooleanField(default=False),
        ),
    ]
