# Generated by Django 5.2.2 on 2025-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManager', '0004_alter_server_last_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_successful_ping',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_ping',
            field=models.DateTimeField(null=True),
        ),
    ]
