# Generated by Django 5.2.2 on 2025-06-17 20:35

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManager', '0005_server_last_successful_ping_alter_server_last_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='auth_key',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
