# Generated by Django 5.2.2 on 2025-06-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManager', '0006_server_auth_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='serverContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('container_id', models.CharField(max_length=200, unique=True)),
                ('image', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerManager.server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='containerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_used', models.BigIntegerField(null=True)),
                ('cpu_used', models.FloatField(null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerManager.servercontainer')),
            ],
        ),
        migrations.CreateModel(
            name='serverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=200, unique=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerManager.server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='serverMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(null=True)),
                ('ram_used', models.BigIntegerField(null=True)),
                ('ram_available', models.BigIntegerField(null=True)),
                ('cpu_used', models.FloatField(null=True)),
                ('disk_used', models.BigIntegerField(null=True)),
                ('disk_available', models.BigIntegerField(null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerManager.server')),
            ],
        ),
    ]
