# Generated by Django 5.2.2 on 2025-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManager', '0007_servercontainer_containermetric_serverinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='kernel_arch',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='kernel_version',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='os',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='platform',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='platform_family',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='platform_version',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='hostname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
