# Generated by Django 5.2.2 on 2025-06-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManager', '0008_serverinfo_kernel_arch_serverinfo_kernel_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containermetric',
            name='ts',
            field=models.DateTimeField(null=True),
        ),
    ]
